### ISSUE TITLE
I believe mediumship stop working even on Chrome.

### ISSUE THREAD

**Issue by KartSriv** [swapagarwal/mediumship#10]
Just like what @itstheandre told in https://github.com/swapagarwal/mediumship/issues/9 but this time in Chrome.

![image](https://user-images.githubusercontent.com/25691607/59571463-920ea800-90c2-11e9-95fc-70b7d1e71828.png)

**Comment by j3soon** [comment]
Chrome v2.1 released, will be published within 60 minutes.

**Comment by itstheandre** [comment]
@j3soon any idea when will be released on Firefox?

**Comment by j3soon** [comment]
@itstheandre The firefox version has already been published! See README for more details. You can either uninstall the old version and install the new one, or simply update it.

**Comment by itstheandre** [comment]
It stopped working again. No chrome or firefox. Just kaput
