### ISSUE TITLE
Firefox and Chrome not working again

### ISSUE THREAD

**Issue by itstheandre** [swapagarwal/mediumship#12]
Well, as explained on #9 and #10 it stopped working. Even after the update. For a few hours was working and now no longer.

**Comment by swapagarwal** [comment]
You have to click the page action button to read the full story. 😇

**Comment by gonz4lex** [comment]
Hi @swapagarwal,

Unfortunately, I can confirm what @itstheandre says. Clicking the page action button reopens the page in a new tab, but the member's only paywall is not removed.

**Comment by itstheandre** [comment]
I did. It's really not working :/. At least for me. I'll probably debabscreeb capture when I get home


+49 178 493 5615
Linkedin [https://www.linkedin.com/in/itstheandre]
You can already listen to the new episode of the Pioneers Show here [https://open.spotify.com/show/556GnaAw1m54rGyUGJQk8K?si=7YLzCUbBRfCA0HTpwtQyoQ] ! On Wed, Jun 19, 2019 at 4:02am, Swapnil Agarwal < notifications@github.com [notifications@github.com] > wrote:
You have to click the page action button to read the full story. 😇

**Comment by swapagarwal** [comment]
Can you try after signing out? 


---- On Wed, 19 Jun 2019 12:27:41 +0530 notifications@github.com wrote ----



Hi @swapagarwal,

Unfortunately, I can confirm what @itstheandre says. Clicking the page action button reopens the page in a new tab, but the member's only paywall is not removed.

**Comment by itstheandre** [comment]
What do you mean? Sign-in out medium? And signing in again?


+49 178 493 5615
Linkedin [https://www.linkedin.com/in/itstheandre]
You can already listen to the new episode of the Pioneers Show here [https://open.spotify.com/show/556GnaAw1m54rGyUGJQk8K?si=7YLzCUbBRfCA0HTpwtQyoQ] ! On Wed, Jun 19, 2019 at 8:58am, Swapnil Agarwal < notifications@github.com [notifications@github.com] > wrote:
Can you try after signing out?


---- On Wed, 19 Jun 2019 12:27:41 +0530 notifications@github.com wrote ----



Hi @swapagarwal,

Unfortunately, I can confirm what @itstheandre says. Clicking the page action button reopens the page in a new tab, but the member's only paywall is not removed.

**Comment by itstheandre** [comment]
@swapagarwal I've tried signing out of medium and reupdating the extension but to no luck

**Comment by j3soon** [comment]
Hi, I can confirm this issue. Maybe try using incognito mode instead or other methods mentioned [here](https://github.com/swapagarwal/mediumship#disclaimer) for now.

**Comment by nicolas-b12** [comment]
Same here, doesn't work anymore...

**Comment by nicolas-b12** [comment]
Update : The method is still valid, if I copy the request as Curl, then add something like `-H 'Referer: https://t.co/9mrinl90sv'` it works

**Comment by KartSriv** [comment]
@swapagarwal I can also confirm that mediumship is not working.

**Comment by nicolas-b12** [comment]
https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin?hl=fr can help...

![Screenshot 2019-06-19 at 17 27 06](https://user-images.githubusercontent.com/41992196/59778827-80dabc80-92b7-11e9-907e-aaa728ae7847.png)

**Comment by j3soon** [comment]
@nicolas-b12 Hi, can you elaborate more details on your approach?

**Comment by nicolas-b12** [comment]
I found that you can't remove all the site rules, you need at least one rule by domain that you want to manipulate.

**Comment by j3soon** [comment]
Thanks @nicolas-b12 ! It's my mistake to remove those permissions. We still need them because of our singly-used background listener! I've roll backed the commit and updated both on Chrome & Firefox, try it out on v2.3.

@itstheandre Try out v2.3, It should work by clicking the button.

**Comment by swapagarwal** [comment]
Thanks @nicolas-b12 for diving into the issue! ❤️

**Comment by swapagarwal** [comment]
@itstheandre Can you confirm it's working for you now?

**Comment by gonz4lex** [comment]
Hi @swapagarwal ,

I can confirm it works on my side (Chrome) whenever clicking the action button, and for domains other than medium.com, i.e. towardsdatascience.com and itnext.io.

Great job from your side guys!

**Comment by itstheandre** [comment]
@swapagarwal good on firefox :)

**Comment by nicolas-b12** [comment]
@swapagarwal @j3soon you're welcome, all credits to you ! You did an amazing job !
