### ISSUE TITLE
Hides the piece of code which is hosted on Github

### ISSUE THREAD

**Issue by dpgc11** [swapagarwal/mediumship#13]
![screenshot-medium com-2019 06 20-12-04-02](https://user-images.githubusercontent.com/13483141/59826861-c600fc00-9354-11e9-9cc0-7d24fc50f776.png)

This is how it looks when I open it in incognito mode: 

![screenshot-medium com-2019 06 20-12-04-57](https://user-images.githubusercontent.com/13483141/59826884-d74a0880-9354-11e9-9f29-df8931b054c4.png)

**Comment by nicolas-b12** [comment]
Can't reproduce, can I have the link to this article ? Are you using Chrome or Firefox ?

**Comment by dpgc11** [comment]
Chrome.

[Here's a link to the article](https://medium.com/better-programming/android-constraintlayout-explained-using-a-complex-ui-861c92479c90)

**Comment by nicolas-b12** [comment]
I still can't reproduce. Can you test with an other device ? Or at least Firefox ?

Also, can you open the developer tools and see in Network if something is going wrong when loading the articles ?

**Comment by swapagarwal** [comment]
Working on me in Chrome.

**Comment by dpgc11** [comment]
After debugging, I found that JS was disabled. After enabling it, it started working.
