### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by ahaq0** [swapagarwal/mediumship#23]
Cleared cookies and did all of the other suggestions to no avail. I guess the vulnerability has been patched?

**Comment by swapagarwal** [comment]
Can you sign out of Medium and try again?

**Comment by ahaq0** [comment]
Yes, no luck. Any other ideas

**Comment by rupinderjeet** [comment]
Works for me.

**Comment by swapagarwal** [comment]
Thanks @rupinderjeet!
